get 'collabora_online/view/:id', to: 'collabora_online#view', as: 'collabora_online_view'
get 'collabora_online/edit/:id', to: 'collabora_online#edit', as: 'collabora_online_edit'
get 'collabora_online/test', to: 'collabora_online#test', as: 'collabora_online_test'
get 'collabora_online/wopi/:attachment_id', to: 'collabora_online#wopi', as: 'collabora_online_wopi'
post 'collabora_online/wopi/:attachment_id', to: 'collabora_online#wopi', as: 'collabora_online_wopi_post'
put 'collabora_online/wopi/:attachment_id', to: 'collabora_online#wopi_put_file', as: 'collabora_online_wopi_put'
get 'collabora_online/wopi/:attachment_id/contents', to: 'collabora_online#wopi_contents', as: 'collabora_online_wopi_contents'
post 'collabora_online/wopi/:attachment_id/contents', to: 'collabora_online#wopi_put_contents', as: 'collabora_online_wopi_put_contents_post'
put 'collabora_online/wopi/:attachment_id/contents', to: 'collabora_online#wopi_put_contents', as: 'collabora_online_wopi_put_contents'
options 'collabora_online/wopi/:attachment_id', to: 'collabora_online#handle_options_request'
options 'collabora_online/wopi/:attachment_id/contents', to: 'collabora_online#handle_options_request'
